baseURL = 'https://rafffle.github.io'
languageCode = 'en-us'
title = 'raphael esquivel'

theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[menu]

  [[menu.main]]
    name = "Home"
    url = ""
    weight = 1
    
  [[menu.main]]
    name="CV"
    url="/cv/english.pdf"
    weight=2

  [[menu.main]]
    name = "Talks and writing"
    url = "talks/"
    weight = 3


# [[menu.main]]
#   name = "Bookshelf"
#   url="books/"
#   weight=4

[params]
  description = "Website built with Hugo."
  footer = "Email: [esquivelralphie@gmail.com](esquivelralphie@gmail.com) | [Github](https://github.com/rafffle) | [LinkedIn](https://www.linkedin.com/in/raphael-rm-esquivel/)"


[markup]

  [markup.goldmark]

    [markup.goldmark.renderer]
      unsafe = true
